(()=>{'use strict';const D=CATALOG,$=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),E=escape,find=id=>D.pages.find(p=>p.id===id);let current='home',editing=null,target=null,loadError='';
function toast(s){$('toast').textContent=s;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',3500)}
function download(name,body,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
function syncText(){return NoteStore.configured()?(loadError?'クラウド通信失敗：'+loadError:NoteStore.author?'クラウド接続／作者ログイン済み':'クラウド閲覧／編集には作者ログインが必要'):NoteStore.local?'このブラウザーだけの仮保存／他PCとは同期しません':'クラウド未設定／メモ編集は無効'}
function nav(){let html='<a href="#home">トップ</a>';for(const g of D.groups){html+='<details'+(g===find(current)?.group||g==='00 INDEX'?' open':'')+'><summary>'+E(g)+'</summary>'+D.pages.filter(p=>p.group===g).map(p=>'<a href="#'+p.id+'" class="'+(current===p.id?'active':'')+'">'+E(p.title)+'</a>').join('')+'</details>'}$('nav').innerHTML=html;}
function header(title,sub=''){return '<div class="eyebrow">MOTHER PRESIDENT / AUTHOR WORKSPACE</div><h1>'+E(title)+'</h1><p class="lead">'+E(sub)+'</p>'}
function tasks(){return '<div class="panel todo"><h2>TODO</h2><p class="meta">'+E(syncText())+'</p>'+D.status.todos.map((t,i)=>{const row=NoteStore.notes.find(n=>n.kind==='todo'&&n.section_id==='todo_'+i);return '<label><input type="checkbox" data-todo="'+i+'" '+(row?.status==='反映済み'?'checked ':'')+(NoteStore.canWrite()?'':'disabled')+'> '+E(t)+'</label>'}).join('')+'<a href="#settings">保存・同期設定</a></div>'}
function status(){return '<div class="grid"><div class="tile"><small>現在フェーズ</small><h3>'+E(D.status.phase)+'</h3></div><div class="tile"><small>資料ページ</small><b>'+D.pages.length+'</b><small>収録数であり完成率ではありません</small></div><div class="tile"><small>ココフォリア</small><b>9 ＋ 1</b><small>元シーン＋確認用読み合わせ。実機未検証</small></div><div class="tile"><small>HO PDF</small><b>未確認</b><small>完成PDFなし／INDD原稿あり</small></div></div><div class="grid"><section class="panel"><h2>ロック済み</h2>'+D.status.locked.map(t=>'<p>'+E(t)+'</p>').join('')+'</section><section class="panel"><h2>未確定・次の作業</h2><ul>'+D.status.pending.map(t=>'<li>'+E(t)+'</li>').join('')+'</ul></section></div><p class="meta">'+E(D.status.completion)+'</p>'}
function home(){return header('『お母さんは大統領』作者用 INDEX','企画・物語・盤面・制作メモを、一つの案内板から。')+'<div class="bar"><span class="badge">'+E(D.status.version)+'</span><span class="meta">更新 '+E(D.status.updated)+'</span><a href="#memos">訂正・メモ一覧</a><a href="#settings">作者ログイン・同期</a></div><div class="alert">作者用・重大なネタバレを含みます。折りたたみはアクセス制御ではありません。旧稿・ロック仕様・レビュー候補を区別して掲載しています。</div>'+status()+tasks()+'<div class="panel"><h2>最終更新</h2><p>資料INDEX化、制作スタジオ成果物の接続、訂正メモ・TODO機能の追加。物語本文は改稿していません。</p><a href="#changelog">更新履歴を見る</a></div>'}
function memoButton(section,title){return '<button class="section-memo" data-memo="'+E(section)+'" data-title="'+E(title)+'">訂正・メモ</button>'}
function documentPage(p){let source='<p class="meta">出典：'+E(p.source||'INDEX整理情報')+' ／ '+E(p.version||'資料案内')+'</p>';let body='<div class="content">'+p.html+'</div>';if(p.secret)body='<details class="spoiler" id="secret"><summary>ネタバレを表示：'+E(p.title)+'</summary>'+body+'</details>';return header(p.title)+source+(p.notice?'<div class="alert">'+E(p.notice)+'</div>':'')+memoButton(p.id,p.title)+body+'<div class="related"><h2>関連資料</h2>'+p.links.map(id=>'<a href="#'+id+'">'+E(find(id)?.title||id)+'</a>').join('')+'</div><div id="pageMemos"></div>'}
function memoCard(n){return '<article class="panel"><div class="bar"><span class="badge" data-status="'+E(n.status)+'">'+E(n.status)+'</span><a href="#'+E(n.page_id)+'">'+E(n.title)+'</a></div><p class="memo-body">'+E(n.body)+'</p><p class="meta">'+E(n.character||'')+' '+E(n.card||'')+' ／ '+E(n.page_id)+' / '+E(n.section_id)+'<br>作成 '+E(n.created_at)+' ／ 更新 '+E(n.updated_at)+'</p><button data-edit="'+E(n.id)+'" '+(NoteStore.canWrite()?'':'disabled')+'>編集</button></article>'}
function memoPage(){return header('訂正・メモ一覧','本文は直接改稿せず、変更案を独立して記録します。')+'<p class="alert">'+E(syncText())+'</p><div class="bar"><button id="reloadNotes">最新を取得</button><button id="exportNotes">修正指示を書き出す</button><button id="backupNotes">全メモJSON保存</button><a href="#settings">同期設定</a></div><div class="filters"><label>状態<select id="filterStatus"><option value="">すべて</option>'+['未対応','対応中','反映済み','保留'].map(x=>'<option>'+x+'</option>').join('')+'</select></label><label>ページ<select id="filterPage"><option value="">すべて</option>'+D.pages.map(p=>'<option value="'+p.id+'">'+E(p.title)+'</option>').join('')+'</select></label><label>人物<select id="filterCharacter"><option value="">すべて</option>'+['サラー','ルーク','ドク','マーティ','ジョン'].map(x=>'<option>'+x+'</option>').join('')+'</select></label><label>カード<input id="filterCard" placeholder="09"></label></div><div id="memoList"></div>'}
function listMemos(){const filter={status:$('filterStatus')?.value,page_id:$('filterPage')?.value,character:$('filterCharacter')?.value,card:$('filterCard')?.value};const rows=NoteStore.notes.filter(n=>n.kind!=='todo'&&Object.entries(filter).every(([k,v])=>!v||n[k]===v));if($('memoList'))$('memoList').innerHTML=rows.map(memoCard).join('')||'<p>該当するメモはありません。</p>'}
function settings(){return header('作者ログイン・同期設定')+'<div class="alert">'+E(syncText())+'</div>'+(NoteStore.configured()?'<form id="loginForm" class="panel"><h2>作者ログイン</h2><label>メール<input id="email" type="email" autocomplete="username" required></label><label>パスワード<input id="password" type="password" autocomplete="current-password" required></label><button>ログイン</button><button type="button" id="logout">ログアウト</button><p id="loginError" role="alert"></p></form><button id="migrate">この端末の仮メモをクラウドへ移行</button>':'<div class="panel"><h2>クラウドDBは未設定です</h2><p>閲覧と検索は利用できます。仮保存は他PCへ同期されません。同期開始にはSupabase設定が必要です。</p><button id="enableLocal">この端末だけの仮保存を有効にする</button><p><a href="pages/setup.html">クラウド設定手順</a></p></div>')+'<p class="design">メモは公開サイトの閲覧者からも参照できる設計です。パスワード・個人情報・非公開の参加者情報を記録しないでください。公開用キーは秘密鍵ではなく、編集権限はDBのRLSで制限します。</p><p>本サイトはシナリオ閲覧のアクセス制御をしません。完全非公開が必要な場合は認証付きホスティングへ移行してください。</p>'}
function downloads(){return header('ダウンロード')+'<div class="alert">FINALとPNGは動作確認用。完成シナリオの本文に差し替えた本番版ではありません。</div>'+D.downloads.map(d=>'<div class="panel"><a href="'+E(d.url)+'" download>'+E(d.name)+'</a><p>'+E(d.note)+' ／ '+(d.bytes/1024/1024).toFixed(1)+' MB</p></div>').join('')+'<p>HO PDFは未制作・未確認。未使用の巨大素材・BGM・他作品素材・INDDは公開対象外です。</p>'}
function render(){current=decodeURIComponent(location.hash.slice(1)||'home');if(!find(current)&&current!=='home')current='home';nav();$('main').innerHTML=current==='home'?home():current==='memos'?memoPage():current==='settings'?settings():current==='todo'?header('TODO')+tasks():current==='status'?header('制作状況')+status():current==='downloads'?downloads():documentPage(find(current));
if(current==='memos'){listMemos();for(const id of ['filterStatus','filterPage','filterCharacter','filterCard'])$(id).oninput=listMemos;$('reloadNotes').onclick=reload;$('exportNotes').onclick=exportInstructions;$('backupNotes').onclick=()=>download('author_memos.json',JSON.stringify(NoteStore.notes,null,2),'application/json');}
if(current==='settings'){if($('enableLocal'))$('enableLocal').onclick=()=>{NoteStore.enableLocal();render()};if($('loginForm'))$('loginForm').onsubmit=async e=>{e.preventDefault();try{await NoteStore.login($('email').value,$('password').value);$('password').value='';loadError='';render()}catch(e){$('password').value='';$('loginError').textContent=e.message}};if($('logout'))$('logout').onclick=async()=>{try{await NoteStore.logout()}catch(e){toast(e.message)}render()};if($('migrate'))$('migrate').onclick=async()=>{try{toast((await NoteStore.migrate())+'件を移行・照合しました')}catch(e){toast(e.message)}};}
const p=find(current);if(p&&$('pageMemos'))$('pageMemos').innerHTML='<h2>この資料のメモ</h2>'+NoteStore.notes.filter(n=>n.page_id===current&&n.kind!=='todo').map(memoCard).join('');
$('main').querySelectorAll('.content [data-section]').forEach(el=>{if(!/^(H2|H3|H4|ARTICLE|DETAILS|TR)$/.test(el.tagName))return;const title=el.querySelector('h3,summary,th')?.textContent||el.textContent.trim().slice(0,60);const b=document.createElement('button');b.className='section-memo';b.textContent='訂正・メモ';b.dataset.memo=el.dataset.section;b.dataset.title=title;(el.tagName==='DETAILS'?el.querySelector('summary'):el.tagName==='TR'?el.querySelector('th,td'):el).append(b)});
$('main').querySelectorAll('.content .maker,.content .knowledge').forEach(el=>{const wrapper=document.createElement('details');wrapper.className='design';const summary=document.createElement('summary');summary.textContent='制作者向け情報・ネタバレを表示';el.before(wrapper);wrapper.append(summary,el)});document.body.classList.remove('menu-open');$('menu').setAttribute('aria-expanded','false');}
function openMemo(section,title,record){if(!NoteStore.canWrite()){toast('編集には作者ログイン、または明示的な仮保存設定が必要です。');location.hash='settings';return}editing=record||null;const p=find(current);target={page_id:record?.page_id||current,section_id:section,title};$('memoTarget').textContent=title+' / '+section;$('memoBody').value=record?.body||'';$('memoStatus').value=record?.status||'未対応';$('memoCharacter').value=record?.character||p?.character||'';$('memoCard').value=record?.card||p?.card||'';$('memoError').textContent='';$('memoDialog').showModal();}
$('memoForm').onsubmit=async e=>{e.preventDefault();const b=$('memoForm').querySelector('button[type=submit]');b.disabled=true;try{await NoteStore.save({...target,id:editing?.id||crypto.randomUUID(),kind:'memo',body:$('memoBody').value,status:$('memoStatus').value,character:$('memoCharacter').value,card:$('memoCard').value},editing);$('memoDialog').close();render();toast(NoteStore.configured()?'クラウドへ保存しました':'この端末に仮保存しました（未同期）')}catch(e){$('memoError').textContent=e.message}finally{b.disabled=false}};$('memoCancel').onclick=()=>$('memoDialog').close();
$('main').addEventListener('click',e=>{const b=e.target.closest('[data-memo],[data-edit]');if(!b)return;e.preventDefault();if(b.dataset.edit){const n=NoteStore.notes.find(n=>n.id===b.dataset.edit);openMemo(n.section_id,n.title,n)}else openMemo(b.dataset.memo,b.dataset.title)});
$('main').addEventListener('change',async e=>{if(!e.target.matches('[data-todo]'))return;const i=Number(e.target.dataset.todo),old=NoteStore.notes.find(n=>n.kind==='todo'&&n.section_id==='todo_'+i);e.target.disabled=true;try{await NoteStore.save({id:old?.id||crypto.randomUUID(),kind:'todo',page_id:'todo',section_id:'todo_'+i,title:D.status.todos[i],body:D.status.todos[i],status:e.target.checked?'反映済み':'未対応',character:'',card:''},old);toast('TODOを保存しました')}catch(err){toast(err.message)}render()});
function exportInstructions(){const rows=NoteStore.notes.filter(n=>n.kind!=='todo'&&n.status==='未対応');let md='# お母さんは大統領 修正指示\n\n未対応メモの書き出し。本文へ未反映の提案であり、実行済みではありません。\n';for(const id of [...new Set(rows.map(r=>r.page_id))]){md+='\n## 修正対象：'+(find(id)?.title||id)+'\n';for(const n of rows.filter(r=>r.page_id===id))md+='\n### '+n.title+'\n対象ID：'+n.page_id+' / '+n.section_id+'\n\n'+n.body+'\n';}download('修正指示_未対応.md',md,'text/markdown');}
async function reload(){try{await NoteStore.load();loadError='';render();toast('最新のメモを取得しました')}catch(e){loadError=e.message;toast(e.message);render()}}
function search(){const q=$('search').value.trim();if(!q){render();return}const secrets=$('secretSearch').checked;const results=D.pages.filter(p=>(p.title+' '+(secrets||!p.secret?p.search:'')).toLowerCase().includes(q.toLowerCase()));$('main').innerHTML=header('検索結果：'+q,results.length+'件／秘密資料の本文検索はチェックで切り替え')+results.map(p=>'<a class="result" href="#'+p.id+'">'+E(p.title)+'<small>'+E(p.group)+' ／ '+E(p.version)+(p.secret?' ／ 秘密資料':'')+'</small></a>').join('');}
$('search').oninput=search;$('secretSearch').onchange=search;$('menu').onclick=()=>{document.body.classList.toggle('menu-open');$('menu').setAttribute('aria-expanded',document.body.classList.contains('menu-open'))};window.addEventListener('hashchange',()=>{$('search').value='';render();window.scrollTo(0,0)});window.addEventListener('storage',()=>{if(!$('memoDialog').open)reload()});window.addEventListener('focus',()=>{if(!$('memoDialog').open)reload()});setInterval(async()=>{if(!NoteStore.configured()||document.hidden||$('memoDialog').open||current==='settings')return;try{await NoteStore.load();loadError='';if(current==='memos')listMemos();if($('pageMemos'))$('pageMemos').innerHTML='<h2>この資料のメモ</h2>'+NoteStore.notes.filter(n=>n.page_id===current&&n.kind!=='todo').map(memoCard).join('');}catch(e){loadError=e.message;}},20000);render();NoteStore.load().then(()=>render()).catch(e=>{loadError=e.message;render()});window.IndexApp={render,exportInstructions};
})();
