(()=>{'use strict';
const D=CATALOG,$=id=>document.getElementById(id),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),find=id=>D.pages.find(p=>p.id===id);let current='home',error='',timers=new Map();
function toast(s){$('toast').textContent=s;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',4500)}
function syncText(){return !NoteStore.configured()?'クラウド接続待ち／共有メモの保存はまだ利用できません':error?'通信エラー：'+error:NoteStore.canWrite()?'編集可能／クラウド保存':'閲覧モード／編集キーで解除できます'}
function download(name,body,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
const header=(title,sub='')=>'<div class="eyebrow">MOTHER PRESIDENT / AUTHOR INDEX</div><h1>'+E(title)+'</h1><p class="lead">'+E(sub)+'</p>',badge=p=>'<span class="badge" data-status="'+E(p.status)+'">'+E(p.status||'資料案内')+'</span>';
function nav(){$('nav').innerHTML='<a href="#home">トップ</a>'+D.groups.map(g=>'<details'+(g===find(current)?.group||g==='00 INDEX'?' open':'')+'><summary>'+E(g)+'</summary>'+['現在版','旧稿','資料案内'].map(status=>{const rows=D.pages.filter(p=>p.group===g&&p.status===status);return rows.length?'<small class="nav-label">'+status+'</small>'+rows.map(p=>'<a href="#'+p.id+'" class="'+(p.id===current?'active':'')+'">'+E(p.title)+'</a>').join(''):''}).join('')+'</details>').join('')}
function source(p){return '<div class="bar">'+badge(p)+'<span class="meta">'+E(p.version)+' ／ '+E(p.source||'制作INDEX')+'</span>'+(p.original?'<a href="'+E(p.original)+'" target="_blank" rel="noopener">原ファイルを開く</a>':'')+'</div>'}
function documentPage(p){return header(p.title)+source(p)+(p.notice?'<p class="alert">'+E(p.notice)+'</p>':'')+'<div class="content" data-document="'+p.id+'">'+p.html+'</div>'+(p.includes||[]).map(id=>{const x=find(id);return '<section class="included"><h2>'+E(x.title)+'</h2>'+source(x)+'<div class="content" data-document="'+x.id+'">'+x.html+'</div></section>'}).join('')+'<div class="related"><h2>関連資料・過去版</h2>'+(p.links||[]).map(id=>'<a href="#'+id+'">'+E(find(id)?.title||id)+'</a>').join('')+'</div>'}
function memoPreview(n){return '<article class="panel"><div class="bar"><a href="#'+E(n.page_id)+'">'+E(n.title)+'</a><span class="badge">'+(n.status==='反映済み'?'反映済み':'未反映')+'</span>'+(n.unsynced?'<span class="badge">この端末の未同期メモ</span>':'')+'</div><p class="memo-body">'+E(n.body)+'</p><small>'+E(n.updated_at)+'</small></article>'}
function status(){return '<div class="grid"><div class="tile"><small>現在版</small><h3>'+E(D.status.version)+'</h3><small>'+E(D.status.updated)+'</small></div><div class="tile"><small>ロック状態</small><p>'+E(D.status.locked.join('／'))+'</p></div><div class="tile"><small>完成状況</small><p>'+E(D.status.completion)+'</p></div><div class="tile"><small>HO PDF</small><p>完成PDF未確認</p><a href="#pdf">収録状況</a></div></div><div class="grid"><div class="panel"><h2>次作業</h2><ul>'+D.status.pending.map(x=>'<li>'+E(x)+'</li>').join('')+'</ul></div><div class="panel"><h2>制作成果物</h2><p><a href="#ccfolia">ココフォリア：確認用実装・実ルーム未検証</a></p><p><a href="#card_01">調査カード：本文12枚／本番PNG未完成</a></p><p><a href="#reading_panel">読み合わせ：原文と工房サンプル</a></p><p><a href="#archive">過去資料・原ファイル</a></p></div></div>'}
function home(){return header('『お母さんは大統領』AUTHOR INDEX','本文・秘密・作者情報は最初から全文表示。資料のすぐ下に作者メモ。')+'<p class="alert">作者向け資料を一般公開中です。URLを知る人以外もアクセスでき、編集キーは閲覧を制限しません。</p><p class="sync-state">'+E(syncText())+'</p>'+status()+'<section class="panel"><h2>4人のHO</h2><div class="bar">'+['sarah','luke','doc','marty'].map(id=>'<a href="#ho_hub_'+id+'">'+E(find('ho_hub_'+id)?.title)+'</a>').join('')+'</div></section>'+tasks()+'<h2>最近の作者メモ</h2>'+NoteStore.notes.filter(n=>n.kind!=='todo').slice(0,5).map(memoPreview).join('')+'<h2>最近更新された資料</h2>'+D.pages.filter(p=>p.updated).sort((a,b)=>b.updated.localeCompare(a.updated)).slice(0,8).map(p=>'<p>'+badge(p)+' <a href="#'+p.id+'">'+E(p.title)+'</a> <small>'+E(p.updated)+'</small></p>').join('')}
function tasks(){return '<section class="panel"><h2>TODO</h2>'+D.status.todos.map((t,i)=>{const n=NoteStore.notes.find(n=>n.kind==='todo'&&n.section_id==='todo_'+i);return '<label><input type="checkbox" data-todo="'+i+'" '+(n?.status==='反映済み'?'checked ':'')+(NoteStore.canWrite()?'':'disabled')+'> '+E(t)+'</label>'}).join('')+'</section>'}
function settings(){return header('編集キー・メモ共有')+'<p class="alert">'+E(syncText())+'</p><form id="keyForm" class="panel"><h2>作者用編集キー</h2><label>編集キー<input id="authorKey" type="password" autocomplete="off" required '+(NoteStore.configured()?'':'disabled')+'></label><button '+(NoteStore.configured()?'':'disabled')+'>編集モードを解除</button><p>キーはサーバーで検証し、ブラウザーには保存しません。解除後は最大30日間の専用トークンだけを保持します。</p><p id="keyError" role="alert"></p></form><div class="panel"><h2>保存・同期</h2><button id="lock">このブラウザーをロック</button> <button id="syncDrafts" '+(NoteStore.canWrite()?'':'disabled')+'>未同期メモを共有保存へ送る</button><p>未同期 '+NoteStore.pending+'件。以前の端末内メモは削除せず保持しています。</p><a href="#drafts">下書きの比較</a><p><a href="pages/setup.html">初回のサーバー設定手順</a></p></div><p>メモも閲覧者へ公開されます。秘密キー・個人情報を書かないでください。</p>'}
function memos(){return header('全メモ一覧','通常は各資料の下から書き込めます。ここは確認・書き出し用です。')+'<div class="bar"><button id="reloadNotes">最新を取得</button><button id="exportNotes">未反映メモを書き出す</button><button id="backupNotes">全メモJSON保存</button><label><input id="unreflected" type="checkbox">未反映だけ</label></div><div id="memoList"></div>'}
function listMemos(){$('memoList').innerHTML=NoteStore.notes.filter(n=>n.kind!=='todo'&&(!$('unreflected').checked||n.status!=='反映済み')).map(memoPreview).join('')||'<p>メモはありません。</p>'}
function draftsPage(){return header('未同期下書きの比較','競合時は自動で上書きしません。内容を確認して選択してください。')+NoteStore.notes.filter(n=>n.unsynced).map(n=>'<section class="panel"><h2>'+E(n.title)+'</h2><div class="grid"><div><h3>この端末の下書き</h3><p class="memo-body">'+E(n.body)+'</p></div><div><h3>クラウド</h3><p class="memo-body">'+E(NoteStore.serverNote(n.id)?.body||'共有メモなし')+'</p></div></div><button data-resolve="'+n.id+'" '+(NoteStore.canWrite()?'':'disabled')+'>下書きを反映して共有保存</button></section>').join('')}
function makeMemo(p,section,title,n){const box=document.createElement('section');box.className='inline-memo';box.dataset.section=section;box.dataset.page=p.id;box.innerHTML='<label>作者メモ <small>'+E(title)+'</small><textarea rows="3" maxlength="12000" '+(NoteStore.canWrite()?'':'disabled')+' placeholder="'+(NoteStore.canWrite()?'ここに訂正・確認内容を記入':'クラウド接続・編集キー解除後に入力できます')+'">'+E(n?.body||'')+'</textarea></label><div class="bar"><button type="button" '+(NoteStore.canWrite()?'':'disabled')+'>保存</button><label><input type="checkbox" '+(n?.status==='反映済み'?'checked ':'')+(NoteStore.canWrite()?'':'disabled')+'>反映済み</label><span class="memo-state" role="status">'+E(n?(n.unsynced?'この端末のみ・未同期 ':'保存済み ')+n.updated_at:syncText())+'</span></div>';const ta=box.querySelector('textarea'),check=box.querySelector('input'),state=box.querySelector('.memo-state');let record=n||{id:crypto.randomUUID()},dirty=false,busy=false,rerun=false;
async function save(){clearTimeout(timers.get(box));timers.delete(box);if(!dirty||!NoteStore.canWrite())return;if(busy){rerun=true;return}busy=true;const value=ta.value,reflected=check.checked;state.textContent='保存中…';try{record=await NoteStore.save({id:record?.id||crypto.randomUUID(),kind:'memo',page_id:p.id,section_id:section,title,body:value,status:reflected?'反映済み':'未反映',character:p.character||'',card:p.card||''},record);dirty=ta.value!==value||check.checked!==reflected;state.textContent=record.unsynced?'未同期：この端末に下書きを保持しました':'保存しました '+new Date(record.updated_at).toLocaleString('ja-JP')}catch(e){state.textContent=e.message;box.classList.add('save-error')}finally{busy=false;if(rerun){rerun=false;save()}}}
ta.oninput=()=>{dirty=true;state.textContent='未保存';clearTimeout(timers.get(box));timers.set(box,setTimeout(save,1800))};ta.onblur=save;check.onchange=()=>{dirty=true;save()};box.querySelector('button').onclick=save;box.flush=save;box.isDirty=()=>dirty;return box}
function mountMemos(){
$('main').querySelectorAll('.content details').forEach(d=>{const s=document.createElement('section');for(const a of d.attributes)s.setAttribute(a.name,a.value);const summary=d.querySelector(':scope > summary');if(summary){const h=document.createElement('h3');h.innerHTML=summary.innerHTML;summary.replaceWith(h)}s.append(...d.childNodes);d.replaceWith(s)});
$('main').querySelectorAll('[data-document]').forEach(content=>{const p=find(content.dataset.document),used=new Set();const insert=(section,title,after)=>{if(used.has(section))return;used.add(section);const matches=NoteStore.notes.filter(n=>n.page_id===p.id&&n.section_id===section&&n.kind!=='todo');for(const n of matches.length?matches:[null]){const box=makeMemo(p,section,title,n);after.after(box);after=box}};
content.querySelectorAll('tr[data-section]').forEach(tr=>{if(!tr.querySelector('td'))return;const title=tr.textContent.trim().slice(0,65),row=document.createElement('tr'),td=document.createElement('td');td.colSpan=tr.children.length;row.append(td);const section=tr.dataset.section,matches=NoteStore.notes.filter(n=>n.page_id===p.id&&n.section_id===section);for(const n of matches.length?matches:[null])td.append(makeMemo(p,section,title,n));tr.after(row);used.add(section)});
for(const h of [...content.querySelectorAll('h2[data-section],h3[data-section],h4[data-section]')]){let last=h;while(last.nextElementSibling&&!/^H[1-4]$/.test(last.nextElementSibling.tagName)&&!last.nextElementSibling.querySelector('[data-section]')&&!last.nextElementSibling.classList.contains('inline-memo'))last=last.nextElementSibling;insert(h.dataset.section,h.textContent.trim(),last)}
for(const n of NoteStore.notes.filter(n=>n.page_id===p.id&&!used.has(n.section_id)&&n.section_id!==p.id&&n.kind!=='todo')){const target=[...content.querySelectorAll('[data-section]')].find(el=>el.dataset.section===n.section_id);insert(n.section_id,n.title,target||content.lastElementChild)}
const matches=NoteStore.notes.filter(n=>n.page_id===p.id&&n.section_id===p.id&&n.kind!=='todo');for(const n of matches.length?matches:[null])content.append(makeMemo(p,p.id,p.title,n));});}
function flush(){document.querySelectorAll('.inline-memo').forEach(b=>b.flush?.())}
function render(){current=decodeURIComponent(location.hash.slice(1)||'home');const p=find(current);if(!p&&!['home','drafts'].includes(current))current='home';nav();$('editState').textContent=NoteStore.canWrite()?'編集可能':'閲覧モード';$('unlock').textContent=NoteStore.canWrite()?'編集設定':'編集モードを解除';$('main').innerHTML=current==='home'?home():current==='settings'?settings():current==='memos'?memos():current==='drafts'?draftsPage():current==='todo'?header('TODO')+tasks():current==='status'?header('制作状況')+status():current==='downloads'?header('ダウンロード')+D.downloads.map(d=>'<p><a href="'+E(d.url)+'" download>'+E(d.name)+'</a> '+E(d.note)+'</p>').join(''):documentPage(p);mountMemos();
if($('keyForm'))$('keyForm').onsubmit=async e=>{e.preventDefault();let key=$('authorKey').value;$('authorKey').value='';try{await NoteStore.unlock(key);key='';render();toast('編集できるようになりました')}catch(e){key='';$('keyError').textContent=e.message}};
if($('lock'))$('lock').onclick=async()=>{try{await NoteStore.lock();render()}catch(e){toast(e.message)}};if($('syncDrafts'))$('syncDrafts').onclick=async()=>{try{toast((await NoteStore.sync())+'件を同期しました');render()}catch(e){toast(e.message)}};
if(current==='memos'){listMemos();$('unreflected').onchange=listMemos;$('reloadNotes').onclick=reload;$('exportNotes').onclick=exportInstructions;$('backupNotes').onclick=()=>download('author_memos.json',JSON.stringify(NoteStore.notes,null,2),'application/json')}
document.body.classList.remove('menu-open');$('menu').setAttribute('aria-expanded','false');}
async function reload(){try{await NoteStore.load();error='';render()}catch(e){error=e.message;toast(e.message)}}
function exportInstructions(){const rows=NoteStore.notes.filter(n=>n.kind!=='todo'&&n.status!=='反映済み');let md='# お母さんは大統領 未反映メモ\n\n';for(const n of rows)md+='## '+(find(n.page_id)?.title||n.page_id)+' / '+n.title+'\n\n'+n.body+'\n\n'+(n.unsynced?'※この端末の未同期メモ\n\n':'');download('未反映メモ.md',md,'text/markdown');return md}
function search(){flush();const q=$('search').value.trim().toLowerCase();if(!q){render();return}const results=D.pages.filter(p=>(p.title+' '+p.search).toLowerCase().includes(q));$('main').innerHTML=header('全文検索',results.length+'件／秘密・作者情報・旧稿を含む')+results.map(p=>'<a class="result" href="#'+p.id+'">'+badge(p)+' '+E(p.title)+'<small>'+E(p.version)+'</small></a>').join('')}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-resolve]');if(b){try{await NoteStore.resolve(b.dataset.resolve);render()}catch(e){toast(e.message)}}});
$('main').addEventListener('change',async e=>{if(!e.target.matches('[data-todo]'))return;const i=+e.target.dataset.todo,old=NoteStore.notes.find(n=>n.kind==='todo'&&n.section_id==='todo_'+i);try{await NoteStore.save({id:old?.id||crypto.randomUUID(),kind:'todo',page_id:'todo',section_id:'todo_'+i,title:D.status.todos[i],body:D.status.todos[i],status:e.target.checked?'反映済み':'未反映'},old)}catch(e){toast(e.message)}});
$('unlock').onclick=()=>{flush();location.hash='settings'};$('search').oninput=search;$('menu').onclick=()=>{document.body.classList.toggle('menu-open');$('menu').setAttribute('aria-expanded',document.body.classList.contains('menu-open'))};window.addEventListener('hashchange',()=>{flush();$('search').value='';render();scrollTo(0,0)});window.addEventListener('beforeunload',e=>{if([...document.querySelectorAll('.inline-memo')].some(b=>b.isDirty?.())){flush();e.preventDefault();e.returnValue=''}});window.addEventListener('online',()=>{if(NoteStore.canWrite())NoteStore.sync().catch(e=>toast(e.message))});
setInterval(async()=>{if(!NoteStore.configured()||document.hidden||document.activeElement?.matches('textarea,input')||[...document.querySelectorAll('.inline-memo')].some(b=>b.isDirty?.()))return;try{await NoteStore.load();error='';if(current==='memos')listMemos()}catch(e){error=e.message}},20000);
render();NoteStore.load().then(()=>render()).catch(e=>{error=e.message;render()});window.IndexApp={render,exportInstructions};
})();
