/* No admin keys. Auth tokens live in this tab only. RLS enforces authorship. */
(()=>{'use strict';const cfg=SITE_CONFIG,key='mother-index-local-v1';let session=null,notes=[],author=false;try{session=JSON.parse(sessionStorage.getItem('mother-index-session')||'null')}catch{}
const configured=()=>!!(cfg.supabaseUrl&&cfg.supabaseKey);let local=localStorage.getItem(key+'-enabled')==='true';
function validate(){if(!/^https:\/\/[a-z0-9-]+\.supabase\.co\/?$/i.test(cfg.supabaseUrl))throw Error('Supabase URLを確認してください。');if(cfg.supabaseKey.startsWith('sb_secret_'))throw Error('管理者キーは使用できません。');if(cfg.supabaseKey.startsWith('ey')){try{const p=JSON.parse(atob(cfg.supabaseKey.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));if(p.role==='service_role')throw Error('service_roleキーは使用できません。')}catch(e){if(e.message.includes('service_role'))throw e;}}}
async function api(path,{method='GET',body,token=true,headers={}}={}){validate();const response=await fetch(cfg.supabaseUrl.replace(/\/$/,'')+path,{method,headers:{apikey:cfg.supabaseKey,...(token&&session?{Authorization:'Bearer '+session.access_token}:{}),'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});const text=await response.text();let json;try{json=JSON.parse(text)}catch{json=text}if(!response.ok)throw Error('クラウド接続エラー '+response.status+'：'+(json.message||json.msg||json.error_description||'設定・ログインを確認してください'));return json;}
async function refreshSession(){if(session&&Date.now()/1000>session.expires_at-90){session=await api('/auth/v1/token?grant_type=refresh_token',{method:'POST',token:false,body:{refresh_token:session.refresh_token}});session.expires_at??=Date.now()/1000+session.expires_in;sessionStorage.setItem('mother-index-session',JSON.stringify(session));}}
async function load(){if(configured()){await refreshSession();author=session?await api('/rest/v1/rpc/is_index_author',{method:'POST',body:{}}):false;notes=await api('/rest/v1/author_notes?select=*&order=updated_at.desc');}else{author=false;notes=JSON.parse(localStorage.getItem(key)||'[]')}return notes;}
async function login(email,password){session=await api('/auth/v1/token?grant_type=password',{method:'POST',token:false,body:{email,password}});session.expires_at??=Date.now()/1000+session.expires_in;sessionStorage.setItem('mother-index-session',JSON.stringify(session));await load();if(!author)throw Error('ログインできましたが、作者権限がありません。DBの作者登録を確認してください。');}
async function logout(){if(configured()&&session)try{await api('/auth/v1/logout',{method:'POST'})}finally{session=null;author=false;sessionStorage.removeItem('mother-index-session')}else{session=null;author=false;sessionStorage.removeItem('mother-index-session')}}
async function save(row,previous){if(!canWrite())throw Error(configured()?'作者ログインが必要です。':'同期設定ページで、この端末だけの仮保存を有効にしてください。');if(configured()){await refreshSession();const body={...row};delete body.updated_at;delete body.created_at;delete body.owner_id;if(previous){const res=await api('/rest/v1/author_notes?id=eq.'+encodeURIComponent(previous.id)+'&updated_at=eq.'+encodeURIComponent(previous.updated_at),{method:'PATCH',body,headers:{Prefer:'return=representation'}});if(!res.length)throw Error('別端末で変更されています。本文を控えて一覧を更新し、内容を比較してください。')}else await api('/rest/v1/author_notes',{method:'POST',body,headers:{Prefer:'return=representation'}});await load();}else{const stamp=new Date().toISOString(),copy={...row,created_at:previous?.created_at||stamp,updated_at:stamp};const latest=JSON.parse(localStorage.getItem(key)||'[]');const index=latest.findIndex(x=>x.id===copy.id);if(previous&&latest[index]?.updated_at!==previous.updated_at)throw Error('別タブで変更されています。一覧を更新してください。');if(index>=0)latest[index]=copy;else latest.push(copy);localStorage.setItem(key,JSON.stringify(latest));notes=latest;}return notes;}
function canWrite(){return configured()?!!author:local}
window.NoteStore={configured,load,login,logout,save,canWrite,get notes(){return notes},get author(){return author},get local(){return local},enableLocal(){if(configured())throw Error('クラウド設定中は仮保存へ切り替えません。');local=true;localStorage.setItem(key+'-enabled','true')},async migrate(){if(!configured()||!author)throw Error('作者ログインが必要です');const pending=JSON.parse(localStorage.getItem(key)||'[]');for(const row of pending){if(notes.some(n=>n.id===row.id))continue;await save(row)}return pending.length;}};
})();
