/* D1 is canonical. Browser storage holds scoped cache, drafts and opaque tokens only. */
(()=>{'use strict';
const cfg=window.SITE_CONFIG,project=cfg.projectId||'mother_president',prefix='mother-index-v3:'+project+':';
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const identity=n=>[n.kind,n.page_id,n.section_id].join('|');
let session=read(prefix+'session',null),cloud=read(prefix+'cache',[]),drafts=[],legacy=[],lastSync=read(prefix+'lastSync',''),lastError='',online=false;
const configured=()=>/^https:\/\//.test(cfg.memoApi||''),canWrite=()=>configured()&&session?.projectId===project&&session.expiresAt>Date.now();
function normalize(n,kind){return {...n,kind,body:n.content||'',status:(kind==='todo'?n.completed:n.resolved)?'反映済み':'未反映',page_id:kind==='todo'?'todo':n.page_id,section_id:kind==='todo'?n.todo_key:n.section_id,title:kind==='todo'?n.label:n.title}}
function local(){const ledger=read(prefix+'migrated',[]);drafts=read(prefix+'outbox',[]);legacy=project==='mother_president'?[...read('mother-index-local-v1',[]),...read('mother-index-outbox-v2',[])].filter(n=>!ledger.includes(n.id)):[]}
local();
async function api(path,method='GET',body){if(!configured())throw Error('クラウド保存先が未設定です。');const url=cfg.memoApi.replace(/\/$/,'')+path+(path.includes('?')?'&':'?')+'projectId='+encodeURIComponent(project);let response;try{response=await fetch(url,{method,headers:{'Content-Type':'application/json',...(session?{Authorization:'Bearer '+session.token}:{})},body:body===undefined?undefined:JSON.stringify({...body,projectId:project}),signal:AbortSignal.timeout(15000)});}catch(e){online=false;lastError='同期できませんでした。端末内の下書きは保持しています。';throw Error(lastError)}const j=await response.json();if(!response.ok){if(j.code==='AUTH_REQUIRED'){session=null;localStorage.removeItem(prefix+'session')}const e=Error(j.error||'同期できませんでした。');e.status=response.status;e.current=j.current;lastError=e.message;throw e}online=true;lastError='';return j}
function notes(){const out=[...cloud];for(const n of legacy)if(!out.some(x=>x.id===n.id))out.push({...n,project_id:project,unsynced:true,legacy:true});for(const n of drafts){const ix=out.findIndex(x=>x.id===n.id||identity(x)===identity(n));const row={...n,unsynced:true};if(ix<0)out.push(row);else out[ix]=row}return out.sort((a,b)=>(b.updated_at||'').localeCompare(a.updated_at||''))}
function queue(n){local();const i=drafts.findIndex(x=>x.id===n.id);if(i<0)drafts.push(n);else drafts[i]=n;write(prefix+'outbox',drafts)}
function stage(row,previous){const stamp=new Date().toISOString();const n={...row,project_id:project,revision:previous?.revision||0,created_at:previous?.created_at||stamp,updated_at:stamp};queue(n);return n}
async function load(){local();if(!configured())return notes();const [m,t]=await Promise.all([api('/api/memos'),api('/api/todos')]);cloud=[...m.memos.map(n=>normalize(n,'memo')),...t.todos.map(n=>normalize(n,'todo'))];lastSync=new Date().toISOString();write(prefix+'cache',cloud);write(prefix+'lastSync',lastSync);return notes()}
async function save(row,previous){if(!canWrite())throw Error('編集キーで解除してください。');const n=stage(row,previous),isTodo=n.kind==='todo',collection=isTodo?'todos':'memos',record=isTodo?{id:n.id,todo_key:n.section_id,label:n.title,completed:n.status==='反映済み',sort_order:Number(n.section_id.replace('todo_',''))||0}:{id:n.id,page_id:n.page_id,section_id:n.section_id,title:n.title,content:n.body,resolved:n.status==='反映済み',character:n.character||'',card:n.card||''};
try{const saved=normalize(await api('/api/'+collection+(n.revision?'/'+encodeURIComponent(n.id):''),n.revision?'PUT':'POST',{[isTodo?'todo':'memo']:record,expectedRevision:n.revision}),n.kind);cloud=cloud.filter(x=>x.id!==saved.id&&identity(x)!==identity(saved)).concat(saved);write(prefix+'cache',cloud);drafts=read(prefix+'outbox',[]).filter(x=>x.id!==n.id||x.updated_at!==n.updated_at);write(prefix+'outbox',drafts);write(prefix+'migrated',[...new Set([...read(prefix+'migrated',[]),n.id])]);local();lastSync=new Date().toISOString();write(prefix+'lastSync',lastSync);return saved}catch(e){if(e.status===409){if(e.current){const c=normalize(e.current,n.kind);cloud=cloud.filter(x=>x.id!==c.id).concat(c)}throw Error('他端末で更新されています。下書きは保持しました。「下書きの比較」で確認してください。')}if(e.status)throw e;return {...n,unsynced:true}}}
async function unlock(key){session=await api('/api/auth/unlock','POST',{key});write(prefix+'session',session);await load()}
async function lock(){try{if(session)await api('/api/auth/lock','POST',{})}finally{session=null;localStorage.removeItem(prefix+'session')}}
function serverNote(id){const draft=notes().find(n=>n.id===id);return cloud.find(n=>n.id===id)||cloud.find(n=>draft&&identity(n)===identity(draft))}
async function resolve(id){await load();const row=notes().find(n=>n.id===id),server=serverNote(id);if(!row)throw Error('下書きが見つかりません。');const saved=await save({...row,id:server?.id||row.id},server);if(saved.unsynced)return saved;drafts=read(prefix+'outbox',[]).filter(n=>n.id!==id);write(prefix+'outbox',drafts);write(prefix+'migrated',[...new Set([...read(prefix+'migrated',[]),id])]);local();return saved}
async function sync(){if(!canWrite())throw Error('編集キーで解除してください。');await load();let count=0;for(const n of notes().filter(n=>n.unsynced)){const saved=await save(n,n);if(!saved.unsynced)count++}return count}
async function backup(){await load();return {schemaVersion:3,projectId:project,exportedAt:new Date().toISOString(),memos:cloud.filter(n=>n.kind==='memo'),todos:cloud.filter(n=>n.kind==='todo')}}
async function restore(data){if(data.projectId!==project||!Array.isArray(data.memos)||!Array.isArray(data.todos))throw Error('この作品のバックアップではありません。');if(!canWrite())throw Error('編集キーで解除してください。');const rows=[...data.memos,...data.todos];if(rows.some(n=>!n||n.project_id!==project||!['memo','todo'].includes(n.kind)||typeof n.page_id!=='string'||typeof n.section_id!=='string'||typeof n.body!=='string'))throw Error('別作品または不正なデータが含まれています。');await load();let imported=0,skipped=0;for(const n of rows){const existing=cloud.find(x=>identity(x)===identity(n));if(existing){skipped++;continue}const saved=await save({...n,id:crypto.randomUUID()},null);if(saved.unsynced)throw Error('復元中に接続が切れました。未同期分は端末下書きに保持しました。再同期してください。');imported++}return {imported,skipped}}
async function health(){return api('/api/health')}
window.NoteStore={configured,canWrite,load,save,stage,unlock,lock,sync,resolve,serverNote,backup,restore,health,get projectId(){return project},get notes(){return notes()},get cloudNotes(){return [...cloud]},get author(){return canWrite()},get pending(){return notes().filter(n=>n.unsynced).length},get syncState(){return {online,lastSync,lastError}},get sessionExpires(){return session?.expiresAt||null}};
})();
