(()=>{'use strict';
const palettes={サラー:['#267a3c','#eef9e9','#76d274'],ルーク:['#167c9e','#e8f9fd','#3cdbf1'],ドク:['#897300','#fffbe3','#ecde2a'],マーティ:['#a81d70','#fff0f8','#f459b2'],共通:['#394550','#f3f5f6','#aebbc7'],事件:['#9c3037','#fff0f0','#ee7777'],EX:['#714c13','#fff8e6','#edc266'],特殊:['#6a3e96','#f7efff','#b68ae0']};
function format(){return Studio.model().cardFormat}function size(){const f=format();return f.preset==='portrait'?{w:600,h:840}:{w:970,h:730}}
function wrap(g,text,width){return String(text||'').split('\n').flatMap(p=>{const a=[];let line='';for(const c of Array.from(p)){if(line&&g.measureText(line+c).width>width){a.push(line);line=c}else line+=c;}a.push(line);return a;});}
async function render(c,side='front'){const f=c[side],{w,h}=size(),scale=format().scale,cv=makeCanvas(w*scale,h*scale),g=cv.getContext('2d'),p=44,pal=palettes[c.colorPreset||c.characterCategory||'共通'],warnings=[];g.scale(scale,scale);g.fillStyle=pal[1];g.fillRect(0,0,w,h);g.fillStyle=pal[0];g.fillRect(0,0,w,118);g.fillStyle=pal[2];g.fillRect(p,136,8,h-215);g.strokeStyle=pal[0];g.lineWidth=8;g.strokeRect(4,4,w-8,h-8);g.textBaseline='top';g.font=`bold ${Math.max(32,f.titleSize)}px "Yu Gothic",sans-serif`;g.fillStyle='#fff';const title=wrap(g,f.title,w-p*2);if(title.length*Math.max(32,f.titleSize)*1.2>92)warnings.push('【文字量超過】タイトル');g.save();g.beginPath();g.rect(p,12,w-p*2,94);g.clip();title.forEach((s,i)=>g.fillText(s,p,18+i*Math.max(32,f.titleSize)*1.2));g.restore();let tw=w-p*2-24,tx=p+24;const ty=164,end=h-92;let imageW=f.image?Math.round(w*.28):0;
if(f.image){const im=new Image();im.src=f.image;try{await im.decode();const s=Math.min(imageW/im.width,(end-ty)/im.height);g.drawImage(im,w-p-imageW+(imageW-im.width*s)/2,ty,im.width*s,im.height*s);tw-=imageW+24;}catch(e){warnings.push('画像読込失敗')}}
const font=Math.max(24,f.fontSize),lh=font*f.lineHeight;g.fillStyle=f.text;g.font=`${font}px "Yu Gothic",sans-serif`;const body=wrap(g,f.body,tw);let y=ty;g.save();g.beginPath();g.rect(tx,ty,tw,end-ty);g.clip();for(const s of body){g.fillText(s,tx,y);y+=lh;}if(f.note){y+=14;g.font=`${Math.max(24,font-4)}px "Yu Gothic",sans-serif`;for(const s of wrap(g,f.note,tw)){g.fillText(s,tx,y);y+=Math.max(24,font-4)*f.lineHeight;}}g.restore();if(y>end)warnings.push('【文字量超過】本文・補足');g.font='20px "Yu Gothic",sans-serif';g.fillStyle=pal[0];const footer=[c.characterCategory||'共通',c.exMark,c.cardId].filter(Boolean).join(' / ');if(g.measureText(footer).width>w-p*2)warnings.push('【文字量超過】下部情報');g.fillText(footer,p,h-56);return {canvas:cv,warnings};}
function target(id){const m=/^(investigation|discussion)_(\d+)$/.exec(id||'');return m?'mp_card_'+(m[1]==='discussion'?1:0)+'_'+(Number(m[2])-1):id;}
function slot(id){GlobalEdit.build();const n=GlobalEdit.get('item:'+target(id));return n?GlobalEdit.world(n):null;}
let boardRev=0;async function board(cv,side){const rev=++boardRev,g=cv.getContext('2d');GlobalEdit.render(g);let count=0;for(const c of CardMaker.cards){const r=slot(c.targetSlot);if(!r)continue;const out=await render(c,side);if(rev!==boardRev)return;const im=out.canvas,s=Math.min(r.w/im.width,r.h/im.height);g.drawImage(im,r.x+(r.w-im.width*s)/2,r.y+(r.h-im.height*s)/2,im.width*s,im.height*s);count++;}document.getElementById('cmPlacement').textContent=`既存スロットへ仮配置 ${count}枚。横長970×730は4.85×3.65と同じ比率。保存済みの位置調整も反映します。`;}
async function apply(c){const id=target(c.targetSlot),e=Studio.data().entities.items[id];if(!e)throw Error('既存カード枠を選択してください');const front=await render(c,'front'),back=await render(c,'back');if(front.warnings.length||back.warnings.length)throw Error([...front.warnings,...back.warnings].join('\n'));checkpoint();e.imageUrl=await Studio.addImage(front.canvas);e.coverImageUrl=await Studio.addImage(back.canvas);draw();}
async function pack(){if(!CardMaker.cards.length)throw Error('カードがありません');const errors=CardMaker.validate();if(errors.length)throw Error(errors.join('\n'));const files=[];for(const c of CardMaker.cards)for(const side of ['front','back']){const out=await render(c,side);if(out.warnings.length)throw Error(c.cardId+'：'+out.warnings.join('\n'));files.push({name:c.cardId+(side==='back'?'_back':'')+'.png',bytes:await canvasPngBytes(out.canvas)});}files.push({name:'card_manifest.json',bytes:new TextEncoder().encode(JSON.stringify({preset:format(),size:size(),cards:CardMaker.cards.map(c=>({cardId:c.cardId,targetSlot:target(c.targetSlot)||null,color:c.colorPreset||c.characterCategory,front:c.cardId+'.png',back:c.cardId+'_back.png'}))},null,2))});return zipStore(files);}
function decorate(c){const form=document.getElementById('cmForm'),f=format();const controls=document.createElement('div');controls.innerHTML=`<h3>全カード共通サイズ</h3><label>出力プリセット<select id="scPreset"><option value="mother">お母さんは大統領・横長（970×730）</option><option value="portrait">縦長（600×840）</option></select></label><label>解像度倍率<select id="scScale"><option value="1">1x</option><option value="2">2x</option></select></label>${c?`<label>キャラクターカテゴリ<select id="scCharacter">${Object.keys(palettes).map(x=>`<option>${x}</option>`).join('')}</select></label><label>色プリセット<select id="scColor">${Object.keys(palettes).map(x=>`<option>${x}</option>`).join('')}</select></label><button id="scApply">このカードを選択枠へ設定</button>`:''}`;form.prepend(controls);const $=id=>document.getElementById(id);$('scPreset').value=f.preset;$('scScale').value=f.scale;$('scPreset').onchange=e=>{checkpoint();f.preset=e.target.value;CardMaker.refresh()};$('scScale').onchange=e=>{checkpoint();f.scale=Number(e.target.value);CardMaker.refresh()};if(c){$('scCharacter').value=c.characterCategory||'共通';$('scColor').value=c.colorPreset||'共通';$('scCharacter').onchange=e=>{checkpoint();c.characterCategory=c.colorPreset=e.target.value;$('scColor').value=e.target.value;CardMaker.refresh()};$('scColor').onchange=e=>{checkpoint();c.colorPreset=e.target.value;CardMaker.refresh()};$('scApply').onclick=async()=>{try{await apply(c);alert('既存の '+target(c.targetSlot)+' に画像を設定しました。ID・位置・サイズは維持しています。')}catch(e){alert(e.message)}};
const sel=form.querySelector('[data-key=targetSlot]');sel.innerHTML='<option value="">未指定</option>'+Object.keys(Studio.data().entities.items).filter(id=>/^mp_card_[01]_\d+$/.test(id)).map(id=>`<option value="${id}">${id}</option>`).join('');sel.value=target(c.targetSlot)||'';}
for(const k of ['padding','background','band','titleColor','imageHeight']){const el=form.querySelector('[data-face='+k+']');if(el)el.closest('label').hidden=true;}
for(const [k,min]of [['fontSize',24],['titleSize',32]]){const el=form.querySelector('[data-face='+k+']');if(el)el.min=min;}
}
document.getElementById('cmAdd').textContent='横長カードを作る';document.querySelector('#cardMaker header b').textContent='カード工房 — 同じサイズで色を使い分ける';document.querySelector('#cardMaker .cmPreview>div p').textContent='全カード共通プリセット。横長970×730／縦長600×840、1x・2x。余白・文字領域は固定で、色だけを変更できます。';for(const id of ['cmBatch','cmPack']){const b=document.getElementById(id);b.textContent='カード画像を書き出す（CARD_PNG.zip）';b.onclick=async()=>{try{downloadBlob(await pack(),'CARD_PNG.zip')}catch(e){alert(e.message)}};}document.getElementById('cmManifest').hidden=true;document.getElementById('cmSample').hidden=true;
window.StudioCards={render,decorate,slot,target,board,apply,pack,size,palettes};
})();
