/* Standalone card authoring. Board content is never mutated by temporary placement. */
(()=>{'use strict';
const types=['事件捜査','議論','EX','初期公開情報','最終推理','その他'];
const slots=[...Array.from({length:10},(_,i)=>'investigation_'+String(i+1).padStart(2,'0')),...Array.from({length:12},(_,i)=>'discussion_'+String(i+1).padStart(2,'0')),...Array.from({length:12},(_,i)=>'ex_'+String(i+1).padStart(2,'0'))];
slots.push(...Array.from({length:10},(_,i)=>'mp_card_0_'+i),...Array.from({length:12},(_,i)=>'mp_card_1_'+i));
let selected=0,side='front',active=false,revision=0;
function model(){state.cardMaker??={version:1,cards:[]};return state.cardMaker;}
function face(title=''){return {title,body:'',note:'',background:'#fff9eb',band:'#283b51',text:'#17202a',titleColor:'#ffffff',image:null,fontSize:28,titleSize:36,padding:32,lineHeight:1.5,imageHeight:230};}
function card(id){return {cardId:id,type:'事件捜査',targetSlot:'',pc:'',exMark:'',width:600,height:840,front:face('新しいカード'),back:face('裏面')};}
function current(){return model().cards[selected];}
const host=document.createElement('section');host.id='cardMaker';host.hidden=true;
host.innerHTML=`<header><b>CARD MAKER / カード工房</b><button id="cmClose">盤面編集へ戻る</button><button id="cmSample">サンプル12枚を追加</button><button id="cmProject">プロジェクトJSON保存</button></header><div class="cmLayout"><aside><select id="cmCards" aria-label="カード一覧"></select><button id="cmAdd">追加</button><button id="cmCopy">複製</button><button id="cmDelete">削除</button><div id="cmForm"></div></aside><main><div class="cmToolbar"><button data-cm-side="front">表面</button><button data-cm-side="back">裏面</button><button id="cmSingle">表示面PNG</button><button id="cmBatch">カード一括PNG（ZIP）</button><button id="cmManifest">manifest保存</button><button id="cmPack">CARD_PACK.zip</button></div><p id="cmWarning" role="status"></p><div class="cmPreview"><canvas id="cmCard" width="600" height="840"></canvas><div><p>600×840の縦長カード。文字は自動縮小しません。文字サイズ・行間・余白を入力して確認できます。</p><p>盤面上では固定スロットに縦横比を維持して仮配置します。拡大したカードと盤面上の縮小表示の両方を確認してください。</p><label>盤面倍率<select id="cmZoom"><option value="fit">画面に合わせる</option><option value="100">100%（1600px）</option></select></label><p id="cmPlacement"></p></div></div><h3>盤面上の仮配置（既存カードは変更しません）</h3><div class="cmBoardScroll"><canvas id="cmBoard" width="1600" height="900"></canvas></div></main></div>`;
document.body.append(host);
const css=document.createElement('style');css.textContent=`#cardMaker[hidden]{display:none}#cardMaker{position:fixed;inset:0;z-index:2000;background:#101821;color:#f0f4f8;display:flex;flex-direction:column}#cardMaker header{display:flex;gap:12px;align-items:center;padding:12px;border-bottom:1px solid #435369;flex-wrap:wrap}#cardMaker button{background:#294560;border:1px solid #61809d;border-radius:5px;color:white;padding:7px 10px;cursor:pointer}#cardMaker button:disabled{opacity:.4;cursor:default}.cmLayout{display:grid;grid-template-columns:330px 1fr;min-height:0;flex:1}.cmLayout>aside,.cmLayout>main{overflow:auto;padding:14px;min-width:0}.cmLayout>aside{border-right:1px solid #435369}.cmToolbar{display:flex;flex-wrap:wrap;gap:6px}.cmPreview{display:flex;align-items:flex-start;gap:20px}.cmPreview>div{max-width:300px;font-size:13px;line-height:1.7}#cmCard{width:360px;height:504px;max-width:100%;border-radius:0;background:#fff;flex-shrink:0}.cmBoardScroll{overflow:auto;border:1px solid #607287}#cmBoard{width:100%;min-width:600px;border-radius:0}#cmWarning{color:#ffd170;white-space:pre-wrap}#cmForm label{display:block;margin:8px 0;font-size:12px}#cmForm textarea{min-height:90px}#cmForm input,#cmForm select,#cmForm textarea{width:100%}#cmForm input[type=color]{height:32px}#cardMaker [data-active=true]{outline:2px solid #76cfff}@media(max-width:800px){.cmLayout{grid-template-columns:260px 1fr}.cmPreview{display:block}#cmCard{width:300px;height:420px}}`;
document.head.append(css);
const button=document.createElement('button');button.textContent='カード工房';button.className='btn';button.id='cardMakerTab';document.querySelector('.topbar').prepend(button);
const $=s=>host.querySelector(s);
const opts=(values,v)=>values.map(x=>`<option value="${esc(x)}" ${x===v?'selected':''}>${esc(x||'未指定')}</option>`).join('');
function form(){const cards=model().cards,c=current();$('#cmCards').innerHTML=cards.map((c,i)=>`<option value="${i}">${esc(c.cardId)} / ${esc(c.front.title)}</option>`).join('');$('#cmCards').value=String(selected);$('#cmForm').innerHTML=c?`<label>カードID<input data-key="cardId" value="${esc(c.cardId)}"></label><label>カード種別<select data-key="type">${opts(types,c.type)}</select></label><label>配置先スロット<select data-key="targetSlot">${opts(['',...slots],c.targetSlot)}</select></label><label>対応PC<select data-key="pc">${opts(['','PC1','PC2','PC3','PC4','全員'],c.pc)}</select></label><label>EXマーク<input data-key="exMark" value="${esc(c.exMark)}"></label><h3>${side==='front'?'表面':'裏面'}の内容</h3>${['title','body','note'].map(k=>`<label>${{title:'タイトル',body:'本文',note:'補足'}[k]}${k==='title'?`<input data-face="${k}" value="${esc(c[side][k])}">`:`<textarea data-face="${k}">${esc(c[side][k])}</textarea>`}</label>`).join('')}${['background','band','text','titleColor'].map(k=>`<label>${{background:'背景色',band:'タイトル帯色',text:'文字色',titleColor:'タイトル文字色'}[k]}<input type="color" data-face="${k}" value="${c[side][k]}"></label>`).join('')}${[['fontSize','本文文字サイズ',12,72],['titleSize','タイトル文字サイズ',16,80],['padding','余白',12,70],['lineHeight','行間倍率',1,2.5],['imageHeight','画像領域の高さ',60,400]].map(([k,label,min,max])=>`<label>${label}<input type="number" min="${min}" max="${max}" step="${k==='lineHeight'?'.1':'1'}" data-face="${k}" value="${c[side][k]}"></label>`).join('')}<label>この面の画像<input id="cmImage" type="file" accept="image/*"></label><button id="cmRemoveImage">画像を外す</button>`:'「追加」または「サンプル12枚を追加」で開始してください。';
host.querySelectorAll('[data-cm-side]').forEach(b=>b.dataset.active=String(b.dataset.cmSide===side));
host.querySelectorAll('[data-key],[data-face]').forEach(el=>el.onchange=()=>{checkpoint();const k=el.dataset.key||el.dataset.face;let v=el.value;if(el.type==='number'){v=Number(v);if(!Number.isFinite(v))return;v=Math.max(Number(el.min),Math.min(Number(el.max),v));el.value=v;}if(el.dataset.key)c[k]=v;else c[side][k]=v;refresh();});
if(c){$('#cmImage').onchange=async e=>{const file=e.target.files[0];if(!file)return;const target=c[side];try{const url=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});const im=new Image();im.src=url;await im.decode();checkpoint();target.image=url;refresh();}catch(e){alert('画像を読み込めませんでした。別の画像を選んでください。')}};$('#cmRemoveImage').onclick=()=>{checkpoint();c[side].image=null;refresh()};}
$('#cmCopy').disabled=$('#cmDelete').disabled=$('#cmSingle').disabled=!c;if(window.StudioCards)StudioCards.decorate(c,side);}
function lines(g,str,width){const result=[];for(const para of String(str||'').split('\n')){let line='';for(const ch of Array.from(para)){if(line&&g.measureText(line+ch).width>width){result.push(line);line=ch}else line+=ch;}result.push(line);}return result;}
async function renderCard(c,which){if(window.StudioCards)return StudioCards.render(c,which);const f=c[which],cv=document.createElement('canvas');cv.width=600;cv.height=840;const g=cv.getContext('2d'),p=f.padding,w=600-2*p,warnings=[];g.fillStyle=f.background;g.fillRect(0,0,600,840);g.fillStyle=f.band;g.fillRect(0,0,600,130);g.textBaseline='top';g.font=`bold ${f.titleSize}px "Yu Gothic",sans-serif`;const ts=lines(g,f.title,w);if(ts.length*f.titleSize*1.2>100)warnings.push('タイトルが収まりません');g.save();g.beginPath();g.rect(p,14,w,100);g.clip();g.fillStyle=f.titleColor;ts.forEach((t,i)=>g.fillText(t,p,18+i*f.titleSize*1.2));g.restore();let y=130+p;
if(f.image){try{const im=new Image();im.src=f.image;await im.decode();const scale=Math.min(w/im.width,f.imageHeight/im.height);g.drawImage(im,p+(w-im.width*scale)/2,y,im.width*scale,im.height*scale);y+=f.imageHeight+18;}catch(e){warnings.push('画像を読み込めません');}}
const textEnd=780-p;g.save();g.beginPath();g.rect(p,y,w,Math.max(0,textEnd-y));g.clip();g.fillStyle=f.text;g.font=`${f.fontSize}px "Yu Gothic",sans-serif`;const body=lines(g,f.body,w);body.forEach((t,i)=>g.fillText(t,p,y+i*f.fontSize*f.lineHeight));if(f.body)y+=body.length*f.fontSize*f.lineHeight;if(f.note){const noteSize=Math.max(12,f.fontSize-4);y+=18;g.font=`${noteSize}px "Yu Gothic",sans-serif`;const ns=lines(g,f.note,w);ns.forEach((t,i)=>g.fillText(t,p,y+i*noteSize*f.lineHeight));y+=ns.length*noteSize*f.lineHeight;}g.restore();if(y>textEnd)warnings.push('本文・補足が収まりません');g.fillStyle=f.text;g.font='18px "Yu Gothic",sans-serif';const footer=[c.pc,c.exMark,c.cardId].filter(Boolean).join(' / ');if(g.measureText(footer).width>w)warnings.push('下部ラベルが収まりません');g.save();g.beginPath();g.rect(p,792,w,30);g.clip();g.fillText(footer,p,798);g.restore();g.strokeStyle=f.band;g.lineWidth=3;g.strokeRect(1.5,1.5,597,837);return {canvas:cv,warnings};}
function validate(){const errors=[],seen=new Set(),assigned=new Set(),files=new Set();for(const c of model().cards){if(!/^[A-Za-z0-9_-]+$/.test(c.cardId))errors.push('カードIDは半角英数字・_・-で指定してください：'+c.cardId);if(seen.has(c.cardId))errors.push('カードID重複：'+c.cardId);seen.add(c.cardId);for(const suffix of ['.png','_back.png']){const filename=(c.cardId+suffix).toLowerCase();if(files.has(filename))errors.push('出力ファイル名重複：'+filename);files.add(filename);}if(c.targetSlot){if(!slots.includes(c.targetSlot))errors.push('不明なスロット：'+c.targetSlot);if(assigned.has(c.targetSlot))errors.push('配置先重複：'+c.targetSlot);assigned.add(c.targetSlot);}}return errors;}
function rect(slot){if(window.StudioCards)return StudioCards.slot(slot);if(!slot)return null;const [kind,num]=slot.split('_'),i=Number(num)-1;const id=kind==='ex'?'ex'+i:kind+'.slot'+i;GlobalEdit.build();const n=GlobalEdit.get(id);return n?GlobalEdit.world(n):null;}
async function refresh(){const rev=++revision,c=current(),warn=validate();if(c){const r=await renderCard(c,side);if(rev!==revision)return;$('#cmCard').width=r.canvas.width;$('#cmCard').height=r.canvas.height;$('#cmCard').style.height='auto';$('#cmCard').getContext('2d').drawImage(r.canvas,0,0);warn.push(...r.warnings);}else $('#cmCard').getContext('2d').clearRect(0,0,600,840);$('#cmWarning').textContent=warn.length?warn.join('\n'):'表示面：収まっています（文字の自動縮小なし）';if(window.StudioCards){await StudioCards.board($('#cmBoard'),side);return;}await board(rev);}
async function board(rev=revision){const g=$('#cmBoard').getContext('2d');if(state.templateId!=='mother_president'){$('#cmPlacement').textContent='固定スロットの仮配置は mother_president 専用です。盤面編集に戻りテンプレートを選択してください。';g.clearRect(0,0,1600,900);return;}GlobalEdit.render(g);let placed=0,unassigned=0;const used=new Set();for(const c of model().cards){if(!c.targetSlot){unassigned++;continue}const r=rect(c.targetSlot);if(!r||used.has(c.targetSlot))continue;used.add(c.targetSlot);const im=await renderCard(c,side);if(rev!==revision)return;g.fillStyle='#202833';g.fillRect(r.x,r.y,r.w,r.h);const s=Math.min(r.w/600,r.h/840);g.drawImage(im.canvas,r.x+(r.w-600*s)/2,r.y+(r.h-840*s)/2,600*s,840*s);placed++;}$('#cmPlacement').textContent=`仮配置 ${placed}枚 / 未配置 ${unassigned}枚。捜査10枠・議論12枠・EX12枠。縦長カードは横長スロット内で小さく見えます。`;}
function manifest(){return {schemaVersion:1,templateId:'mother_president',cardSize:{width:600,height:840},cards:model().cards.map(c=>({cardId:c.cardId,type:c.type,targetSlot:c.targetSlot||null,front:'cards/'+c.cardId+'.png',back:'cards/'+c.cardId+'_back.png',pc:c.pc,exMark:c.exMark,title:c.front.title,frontText:{title:c.front.title,body:c.front.body,note:c.front.note},backText:{title:c.back.title,body:c.back.body,note:c.back.note}}))};}
async function pack(){const errs=validate();if(!model().cards.length)errs.push('カードがありません');if(errs.length)throw Error(errs.join('\n'));const files=[],warnings=[];for(const c of model().cards)for(const s of ['front','back']){const r=await renderCard(c,s);warnings.push(...r.warnings.map(w=>c.cardId+' '+s+'：'+w));files.push({name:'cards/'+c.cardId+(s==='back'?'_back':'')+'.png',bytes:await canvasPngBytes(r.canvas)});}if(warnings.length)throw Error(warnings.join('\n')+'\n文字量・サイズ・余白を調整してから出力してください。');const enc=new TextEncoder();files.push({name:'card_manifest.json',bytes:enc.encode(JSON.stringify(manifest(),null,2))},{name:'README.txt',bytes:enc.encode('CARD_PACK / 600x840 PNG\n各カードの表裏をcards/に収録。割当先はcard_manifest.jsonのtargetSlotを参照。\nスロット未指定はnull。盤面への自動合成は行いません。\nこのZIPはココフォリアのルームZIPではありません。画像素材として使用してください。\n')});return zipStore(files);}
function sample(){checkpoint();const existing=new Set(model().cards.map(c=>c.cardId));for(let i=0;i<12;i++){let id='sample_'+String(i+1).padStart(2,'0');while(existing.has(id))id+='x';existing.add(id);const c=card(id);c.targetSlot=(i<10?'investigation_':'discussion_')+String(i<10?i+1:i-9).padStart(2,'0');if(model().cards.some(x=>x.targetSlot===c.targetSlot))c.targetSlot='';c.front.title='サンプル調査カード '+(i+1);c.front.body='動作確認用の仮文章です。実シナリオの本文ではありません。\n\n机の上に置かれたメモを確認する。記された時刻と証言を照らし合わせよう。';c.front.note='サンプル：必要に応じて本文を差し替えてください。';c.pc='PC'+(i%4+1);c.back.title='未公開情報';c.back.body='このカードの表面は、公開するタイミングに合わせて確認してください。';model().cards.push(c);}selected=model().cards.length-12;form();refresh();}
button.onclick=()=>{active=true;host.hidden=false;form();refresh()};$('#cmClose').onclick=()=>{active=false;host.hidden=true;draw()};$('#cmCards').onchange=e=>{selected=Number(e.target.value);form();refresh()};$('#cmAdd').onclick=()=>{checkpoint();let i=1;while(model().cards.some(c=>c.cardId==='card_'+i))i++;model().cards.push(card('card_'+i));selected=model().cards.length-1;form();refresh()};$('#cmCopy').onclick=()=>{const c=current();if(!c)return;checkpoint();const d=structuredClone(c);d.cardId+='_copy';while(model().cards.some(x=>x.cardId===d.cardId))d.cardId+='x';d.targetSlot='';model().cards.push(d);selected=model().cards.length-1;form();refresh()};$('#cmDelete').onclick=()=>{if(!current()||!confirm('選択カードを削除しますか？'))return;checkpoint();model().cards.splice(selected,1);selected=Math.max(0,selected-1);form();refresh()};$('#cmSample').onclick=sample;$('#cmProject').onclick=saveProject;
host.querySelectorAll('[data-cm-side]').forEach(b=>b.onclick=()=>{side=b.dataset.cmSide;form();refresh()});
$('#cmZoom').onchange=e=>{$('#cmBoard').style.width=e.target.value==='100'?'1600px':'100%'};
$('#cmSingle').onclick=async()=>{if(!current())return;const r=await renderCard(current(),side);if(r.warnings.length){alert(r.warnings.join('\n'));return;}downloadBlob(new Blob([await canvasPngBytes(r.canvas)],{type:'image/png'}),current().cardId+(side==='back'?'_back':'')+'.png')};
$('#cmManifest').onclick=()=>{const errs=validate();if(errs.length){alert(errs.join('\n'));return}downloadBlob(new Blob([JSON.stringify(manifest(),null,2)],{type:'application/json'}),'card_manifest.json')};
for(const id of ['cmBatch','cmPack'])$('#'+id).onclick=async()=>{const b=$('#'+id);b.disabled=true;try{downloadBlob(await pack(),id==='cmPack'?'CARD_PACK.zip':'cards_png.zip')}catch(e){alert(e.message)}finally{b.disabled=false}};
const oldRefresh=refreshAllEditors;refreshAllEditors=function(){oldRefresh();if(active){selected=Math.min(selected,Math.max(0,model().cards.length-1));form();refresh()}};
window.CardMaker={sample,renderCard,pack,manifest,validate,refresh,get cards(){return model().cards},open(){button.click()},form};
})();
