/* Authoring-only panel pack. Never creates room entities or changes board panels. */
(()=>{'use strict';
const kinds=['HO本マーク','カーチェイス本マーク','追加HO本マーク','EX本マーク','読み合わせ表示枠','固定スクリーンパネル','その他小型UI'];
let selected=0,active=false,revision=0;
function model(){state.markerMaker??={version:1,panels:[]};return state.markerMaker;}
function current(){return model().panels[selected];}
function create(id,type='その他小型UI'){return {id,name:id,type,entityType:type==='固定スクリーンパネル'?'screen':'marker',image:null,width:type==='読み合わせ表示枠'?800:160,height:type==='読み合わせ表示枠'?450:120,x:0,y:0,zIndex:150,fixed:true,preserveIdAcrossScenes:true,replaceableImage:true};}
const host=document.createElement('section');host.id='markerMaker';host.hidden=true;
host.innerHTML=`<header><b>MARKER / SCREEN PANEL MAKER — マーカー工房</b><button id="mmClose">盤面編集へ戻る</button><button id="mmProject">プロジェクトJSON保存</button></header><div class="mmLayout"><aside><label>パネル一覧<select id="mmList"></select></label><button id="mmAdd">新規作成</button><button id="mmReading">reading_panel作成</button><button id="mmDuplicate">複製</button><button id="mmDelete">削除</button><div id="mmForm"></div></aside><main><div class="mmToolbar"><button id="mmPng">個別PNG</button><button id="mmManifest">marker_manifest.json</button><button id="mmPack">MARKER_PACK.zip</button></div><p id="mmStatus" role="status"></p><div class="mmPreview"><canvas id="mmCanvas" width="160" height="120"></canvas></div><p>画像は縦横比を維持して枠内に配置します。透明部分はPNGでも透明です。初期座標・重なり順・固定設定はmanifestに保存します。</p><p>「同一IDを維持」がONなら、シーンを跨いでも同じIDを参照する設計です。画像を変更してもIDは自動変更されません。これは素材パックであり、既存ルームを書き換える機能ではありません。</p><h3>初期配置の確認（1600×900）</h3><div class="mmBoardWrap"><canvas id="mmBoard" width="1600" height="900"></canvas></div><p>配置確認は独立したグレーの盤面です。既存テンプレートへの挿入・ZIP合成は行いません。</p></main></div>`;
document.body.append(host);
const css=document.createElement('style');css.textContent=`#markerMaker[hidden]{display:none}#markerMaker{position:fixed;inset:0;z-index:2100;background:#111923;color:#eef4fc;display:flex;flex-direction:column}#markerMaker header{padding:12px;display:flex;gap:12px;align-items:center;flex-wrap:wrap;border-bottom:1px solid #435368}.mmLayout{display:grid;grid-template-columns:330px 1fr;flex:1;min-height:0}.mmLayout>aside,.mmLayout>main{overflow:auto;padding:16px;min-width:0}.mmLayout>aside{border-right:1px solid #435368}#markerMaker label{display:block;margin:8px 0;font-size:13px}#markerMaker input:not([type=checkbox]),#markerMaker select{width:100%;padding:6px;background:#0d1520;color:#fff;border:1px solid #526780;border-radius:4px}#markerMaker input[type=checkbox]{width:auto;margin-right:6px}#markerMaker button{padding:7px 10px;margin:3px;background:#294560;border:1px solid #61809d;border-radius:5px;color:white;cursor:pointer}#markerMaker button:disabled{opacity:.4;cursor:default}#mmStatus{white-space:pre-wrap;color:#ffd983}.mmPreview{padding:16px;background:repeating-conic-gradient(#d9dfe6 0% 25%,#fff 0% 50%) 0/20px 20px;display:inline-block;max-width:100%;overflow:auto}#mmCanvas{width:auto;height:auto;max-width:100%;max-height:480px;aspect-ratio:auto;border-radius:0;background:transparent}#mmBoard{width:100%;min-width:640px;border-radius:0}.mmBoardWrap{overflow:auto}.mmLayout main>p{font-size:13px;line-height:1.7;max-width:960px}@media(max-width:800px){.mmLayout{grid-template-columns:250px 1fr}}`;
document.head.append(css);
const button=document.createElement('button');button.id='markerMakerTab';button.className='btn';button.textContent='マーカー工房';document.querySelector('.topbar').prepend(button);
const $=s=>host.querySelector(s),options=(a,v)=>a.map(x=>`<option value="${esc(x)}" ${x===v?'selected':''}>${esc(x)}</option>`).join('');
function validate(panels=model().panels){const errors=[],ids=new Set();for(const p of panels){if(!/^[A-Za-z0-9_-]{1,80}$/.test(p.id))errors.push('IDは80文字以内の半角英数字・_・-で指定してください：'+p.id);const id=String(p.id).toLowerCase();if(ids.has(id))errors.push('ID重複：'+p.id);ids.add(id);if(!p.name.trim())errors.push(p.id+'：名前がありません');if(!['marker','screen'].includes(p.entityType))errors.push(p.id+'：パネル種別が不正です');for(const [key,min,max]of [['width',16,1600],['height',16,900],['x',-1600,3200],['y',-900,1800],['zIndex',-10000,10000]])if(!Number.isInteger(p[key])||p[key]<min||p[key]>max)errors.push(p.id+'：'+key+'の値が範囲外です');}return errors;}
async function renderPanel(p){const errors=validate([p]);if(errors.length)throw Error(errors.join('\n'));const c=makeCanvas(p.width,p.height),g=c.getContext('2d');if(p.image){const im=new Image();im.src=p.image;try{await im.decode()}catch(e){throw Error(p.id+'：画像を読み込めません');}const scale=Math.min(c.width/im.width,c.height/im.height);g.drawImage(im,(c.width-im.width*scale)/2,(c.height-im.height*scale)/2,im.width*scale,im.height*scale);}else{g.fillStyle='#eff3f9';g.fillRect(0,0,c.width,c.height);g.strokeStyle='#334c68';g.lineWidth=Math.min(4,c.width/8);g.strokeRect(2,2,c.width-4,c.height-4);g.fillStyle='#334c68';g.font=`bold ${Math.max(10,Math.min(32,c.height/7))}px sans-serif`;g.textAlign='center';g.textBaseline='middle';g.fillText(p.type==='読み合わせ表示枠'?'READING PANEL':'IMAGE PLACEHOLDER',c.width/2,c.height/2,c.width-12);}return c;}
function form(){const p=current();$('#mmList').innerHTML=model().panels.map((p,i)=>`<option value="${i}">${esc(p.id)} / ${esc(p.name)}</option>`).join('');$('#mmList').value=selected;$('#mmForm').innerHTML=p?`<label>ID（画像差し替えでは変更しない）<input data-mm="id" value="${esc(p.id)}"></label><label>名前<input data-mm="name" value="${esc(p.name)}"></label><label>用途<select data-mm="type">${options(kinds,p.type)}</select></label><label>パネル種別<select data-mm="entityType"><option value="marker" ${p.entityType==='marker'?'selected':''}>マーカーパネル</option><option value="screen" ${p.entityType==='screen'?'selected':''}>スクリーンパネル</option></select></label>${[['width','幅',16,1600],['height','高さ',16,900],['x','初期x',-1600,3200],['y','初期y',-900,1800],['zIndex','z-index',-10000,10000]].map(([key,label,min,max])=>`<label>${label}<input type="number" step="1" min="${min}" max="${max}" data-mm="${key}" value="${p[key]}"></label>`).join('')}${[['fixed','固定（OFFで可動）'],['preserveIdAcrossScenes','シーンを跨いで同一IDを維持'],['replaceableImage','画像差し替え対象']].map(([key,label])=>`<label><input type="checkbox" data-mm="${key}" ${p[key]?'checked':''}>${label}</label>`).join('')}<label>画像を登録／差し替え<input id="mmImage" type="file" accept="image/*"></label><button id="mmClearImage">画像を外す</button><label>正式本マーク素材<select id="mmBookAsset"><option value="">素材を選択</option>${['PC1 HO','PC1 カーチェイス','PC1 追加HO','PC2 HO','PC2 カーチェイス','PC2 追加HO','PC3 HO','PC3 カーチェイス','PC3 追加HO','PC4 HO','PC4 カーチェイス','PC4 追加HO','EX 黒本'].map((x,i)=>`<option value="${i}">${x}</option>`).join('')}</select></label>`:'「新規作成」または「reading_panel作成」で開始します。';for(const id of ['mmDuplicate','mmDelete','mmPng'])$('#'+id).disabled=!p;
host.querySelectorAll('[data-mm]').forEach(el=>el.onchange=()=>{checkpoint();const k=el.dataset.mm;p[k]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;refresh()});
if(p){$('#mmImage').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const url=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});const im=new Image();im.src=url;await im.decode();checkpoint();p.image=url;refresh()}catch(e){alert('画像を読み込めませんでした。元の画像は保持しています。')}};$('#mmClearImage').onclick=()=>{checkpoint();p.image=null;refresh()};$('#mmBookAsset').onchange=e=>{if(e.target.value==='')return;checkpoint();const i=Number(e.target.value);p.image=i===12?MOTHER_ASSETS.book:MOTHER_ASSETS['icon'+Math.floor(i/3)+'_'+i%3];refresh()};}}
async function refresh(){const rev=++revision,p=current(),errors=validate(),status=[...errors];const cv=$('#mmCanvas');cv.getContext('2d').clearRect(0,0,cv.width,cv.height);if(p){try{const c=await renderPanel(p);if(rev!==revision)return;cv.width=c.width;cv.height=c.height;cv.getContext('2d').drawImage(c,0,0);}catch(e){status.push(e.message)}if(!p.image)status.push('仮画像です。読み合わせ本文は生成していません。後から画像を差し替えてください。');if(p.x<0||p.y<0||p.x+p.width>1600||p.y+p.height>900)status.push('このパネルは1600×900の盤面からはみ出します。');status.push('ID：'+p.id+' / '+(p.fixed?'固定':'可動')+' / '+(p.preserveIdAcrossScenes?'シーン共通ID':'シーン別ID方針'));}
$('#mmStatus').textContent=status.length?status.join('\n'):'パネルを作成してください。';const g=$('#mmBoard').getContext('2d');g.fillStyle='#bfc7d1';g.fillRect(0,0,1600,900);for(const q of [...model().panels].sort((a,b)=>a.zIndex-b.zIndex)){try{const c=await renderPanel(q);if(rev!==revision)return;g.drawImage(c,q.x,q.y);}catch(e){}}$('#mmList').querySelectorAll('option').forEach((o,i)=>o.textContent=model().panels[i].id+' / '+model().panels[i].name);}
function manifest(panels=model().panels){return {schemaVersion:1,packType:'marker_screen_assets',coordinateSpace:{width:1600,height:900,unit:'px'},roomImportReady:false,panels:panels.map(p=>({id:p.id,name:p.name,type:p.type,entityType:p.entityType,image:'panels/'+p.id+'.png',width:p.width,height:p.height,x:p.x,y:p.y,zIndex:p.zIndex,fixed:p.fixed,preserveIdAcrossScenes:p.preserveIdAcrossScenes,replaceableImage:p.replaceableImage,identityPolicy:p.preserveIdAcrossScenes?'shared':'per_scene',sharedEntityId:p.preserveIdAcrossScenes?p.id:null,sceneScopedIdPattern:p.preserveIdAcrossScenes?null:p.id+'__{sceneId}',isPlaceholder:!p.image}))};}
async function pack(){const panels=structuredClone(model().panels),errors=validate(panels);if(!panels.length)errors.push('パネルがありません');if(errors.length)throw Error(errors.join('\n'));const files=[],enc=new TextEncoder();for(const p of panels)files.push({name:'panels/'+p.id+'.png',bytes:await canvasPngBytes(await renderPanel(p))});files.push({name:'marker_manifest.json',bytes:enc.encode(JSON.stringify(manifest(panels),null,2))},{name:'README.txt',bytes:enc.encode('MARKER_PACK：独立した画像素材パックです。ルームZIPではありません。\n同一ID維持がONのパネルは、既存IDを参照したまま画像を置換する方針です。\n画像登録時にIDは変更しません。IDを手動変更すると別のパネルとして扱われる可能性があります。\nシーン別IDが必要な場合はmanifestのsceneScopedIdPatternを今後の合成側で使用します。ここではシーンごとのエンティティを作成しません。\nfixed、zIndex等は配置メタ情報です。ココフォリアへの適用・ZIP合成は未実装。\nisPlaceholder=trueは仮画像です。読み合わせPNGは後から差し替えてください。\n編集再開にはアプリで保存したプロジェクトJSONを使用してください。\n')});return zipStore(files);}
function add(type='その他小型UI',id=null){checkpoint();if(!id){let i=1;while(model().panels.some(p=>p.id.toLowerCase()==='panel_'+i))i++;id='panel_'+i;}const existing=model().panels.findIndex(p=>p.id.toLowerCase()===id.toLowerCase());if(existing>=0){selected=existing;form();refresh();return}model().panels.push(create(id,type));selected=model().panels.length-1;form();refresh();}
button.onclick=()=>{active=true;host.hidden=false;form();refresh()};$('#mmClose').onclick=()=>{active=false;host.hidden=true;draw()};$('#mmProject').onclick=saveProject;$('#mmAdd').onclick=()=>add();$('#mmReading').onclick=()=>add('読み合わせ表示枠','reading_panel');$('#mmList').onchange=e=>{selected=Number(e.target.value);form();refresh()};$('#mmDuplicate').onclick=()=>{const p=current();if(!p)return;checkpoint();const q=structuredClone(p);q.id+='_copy';while(model().panels.some(x=>x.id.toLowerCase()===q.id.toLowerCase()))q.id+='x';model().panels.push(q);selected=model().panels.length-1;form();refresh()};$('#mmDelete').onclick=()=>{if(!current()||!confirm('選択パネルを削除しますか？'))return;checkpoint();model().panels.splice(selected,1);selected=Math.max(0,selected-1);form();refresh()};
$('#mmPng').onclick=async()=>{const p=current();if(!p)return;try{downloadBlob(new Blob([await canvasPngBytes(await renderPanel(p))],{type:'image/png'}),p.id+'.png')}catch(e){alert(e.message)}};
$('#mmManifest').onclick=()=>{const errors=validate();if(!model().panels.length)errors.push('パネルがありません');if(errors.length){alert(errors.join('\n'));return}downloadBlob(new Blob([JSON.stringify(manifest(),null,2)],{type:'application/json'}),'marker_manifest.json')};
$('#mmPack').onclick=async()=>{const b=$('#mmPack');b.disabled=true;try{downloadBlob(await pack(),'MARKER_PACK.zip')}catch(e){alert(e.message)}finally{b.disabled=false}};
const previous=refreshAllEditors;refreshAllEditors=function(){previous();if(active){selected=Math.min(selected,Math.max(0,model().panels.length-1));form();refresh()}};
window.MarkerMaker={open(){button.click()},add,renderPanel,refresh,manifest,pack,validate,get panels(){return model().panels}};
})();
