/* Existing FINAL room is authoritative. No template regeneration or pack merge. */
(()=>{'use strict';
const source=SOURCE_FINAL,enc=new TextEncoder(),baseNodes=PackAssembler.nodes;
function model(){return state.studio??={version:1,sourceHash:source.sha256,originalScenes:Object.keys(source.data.entities.scenes),sceneOrder:Object.keys(source.data.entities.scenes).sort((a,b)=>source.data.entities.scenes[a].order-source.data.entities.scenes[b].order),sceneMeta:{},cardFormat:{preset:'mother',scale:1},readPages:[],characters:null};}
function initialize(){state.packAssembler={version:1,sources:[],choices:{},primary:null,geometry:'base',active:true,scene:source.data.entities.room.sceneId,result:{data:structuredClone(source.data),assets:{...source.assets},log:[],fits:{}}};state.layoutOverrides??={};state.layoutOverrides.assembled={};model();}
initialize();const data=()=>PackAssembler.model.result.data,assets=()=>PackAssembler.model.result.assets;
function scene(){return PackAssembler.model.scene;}
PackAssembler.nodes=function(){const ns=baseNodes();if(!state.studio)return ns;for(let i=1;i<=4;i++){const root=ns.find(n=>n.id==='item:mp_node_pc'+i);if(!root)continue;const id='pcgroup'+i;ns.push({id,label:'PC'+i+' パネル全体',base:{...root.base},parent:null,z:root.z,paint(){}});for(const n of ns){if(n.id==='item:mp_node_pc'+i||n.id.startsWith('item:mp_node_pc'+i+'_')||n.id.startsWith('marker:mp_ho_'+(i-1)+'_'))n.parent=id;}}return ns;};
async function ready(){await Promise.all(Object.values(assets()).map(url=>loadImg(url).decode()));refreshAllEditors();}
async function addImage(c){const bytes=await canvasPngBytes(c),name=await sha256HexBytes(bytes)+'.png';let str='';for(let i=0;i<bytes.length;i+=32768)str+=String.fromCharCode(...bytes.subarray(i,i+32768));assets()[name]='data:image/png;base64,'+btoa(str);data().resources[name]={type:'image/png'};await loadImg(assets()[name]).decode();return name;}
function adjusted(){const result=structuredClone(data()),old=scene(),o=state.layoutOverrides?.assembled||{};function dirty(n){return !!o[n.id]||(n.parent&&dirty(GlobalEdit.get(n.parent)));}function apply(kind,id,e){const n=GlobalEdit.get(kind+':'+id);if(!n||!dirty(n))return;const r=GlobalEdit.world(n);Object.assign(e,p2g(r.x,r.y,r.w,r.h));if(o[n.id]?.z!==undefined)e.z=o[n.id].z;if(o[n.id]?.locked!==undefined)e.locked=e.freezed=o[n.id].locked;let parent=n.parent;while(parent){if(o[parent]?.z!==undefined)e.z+=o[parent].z-GlobalEdit.get(parent).z;if(o[parent]?.locked===true)e.locked=e.freezed=true;parent=GlobalEdit.get(parent).parent;}}
for(const sid of model().sceneOrder){PackAssembler.model.scene=sid;GlobalEdit.build();for(const [id,e]of Object.entries(result.entities.scenes[sid].markers||{}))apply('marker',id,e);}PackAssembler.model.scene=old;GlobalEdit.build();for(const [id,e]of Object.entries(result.entities.items))apply('item',id,e);const originalOrder=model().originalScenes;if(JSON.stringify(model().sceneOrder)!==JSON.stringify(originalOrder))model().sceneOrder.forEach((sid,i)=>result.entities.scenes[sid].order=i+1);result.entities.room.sceneId=old;result.entities.room.markers=structuredClone(result.entities.scenes[old].markers);return result;}
async function finalZip(){const d=adjusted(),files=[],needed=new Set();function scan(x){if(!x||typeof x!=='object')return;for(const [k,v]of Object.entries(x)){if(['imageUrl','coverImageUrl','backgroundUrl','foregroundUrl'].includes(k)&&v)needed.add(v);else if(typeof v==='object')scan(v)}}scan(d.entities);for(const name of needed)if(!assets()[name])throw Error('画像参照欠落：'+name);d.resources={};for(const name of needed){d.resources[name]={type:'image/png'};files.push({name,bytes:Uint8Array.from(atob(assets()[name].split(',')[1]),c=>c.charCodeAt(0))});}files.unshift({name:'__data.json',bytes:enc.encode(JSON.stringify(d))},{name:'.token',bytes:enc.encode('0.'+await sha256HexBytes(crypto.getRandomValues(new Uint8Array(32))))});return zipStore(files);}
async function insert(page,after,reference=after){if(!data().entities.scenes[reference]?.markers?.reading_panel)throw Error('基準シーンにreading_panelがありません');const rendered=await ReadingStudio.render(page);if(rendered.warnings.length)throw Error(rendered.warnings.join('\n'));checkpoint();let i=1,id;do{id='read_scene_'+String(i++).padStart(3,'0')}while(data().entities.scenes[id]);const s=structuredClone(data().entities.scenes[reference]);s.name=ReadingStudio.filename(page).replace('.png','');s.markers.reading_panel.imageUrl=await addImage(rendered.canvas);data().entities.scenes[id]=s;model().sceneMeta[id]={kind:'reading',base:reference,pageId:page.id};const index=model().sceneOrder.indexOf(after);model().sceneOrder.splice(index+1,0,id);refreshSceneUI();return id;}
async function hideReading(id){if(!data().entities.scenes[id]?.markers?.reading_panel)throw Error('reading_panelがありません');checkpoint();const c=makeCanvas(2,2);data().entities.scenes[id].markers.reading_panel.imageUrl=await addImage(c);refreshSceneUI();draw();}
function reorder(from,to){if(from===to)return;const list=model().sceneOrder,i=list.indexOf(from);if(i<0||!list.includes(to))return;checkpoint();list.splice(i,1);list.splice(list.indexOf(to),0,from);refreshSceneUI();}
const nav=document.createElement('header');nav.id='studioNav';nav.innerHTML=`<strong>お母さんは大統領 制作スタジオ</strong><nav><button id="stBoard">1 盤面編集</button><button id="stCards">2 カード工房</button><button id="stReading">3 読み合わせ工房</button><button id="stScenes">4 シーン編集／書き出し</button></nav><div class="stGuide">①盤面を調整 → ②横長カードを作る・設定 → ③読み合わせ画像を作る → ④シーンの間に追加・並び替え → ⑤ZIPを書き出す</div><button id="stSave">プロジェクトJSON保存</button><button id="stLoad">プロジェクトJSON読込</button><label>別のFINAL_CCFOLIAを開く <input id="stImport" type="file" accept=".zip"></label><span id="stStatus">基礎ZIP読込中…</span>`;document.body.prepend(nav);
const modal=document.createElement('section');modal.id='sceneStudio';modal.hidden=true;modal.innerHTML=`<header><b>シーン編集／書き出し</b><button id="ssClose">盤面編集へ戻る</button><button id="ssZip">ココフォリアZIPを書き出す</button><button id="ssPng">プレビューPNG</button><button id="ssSave">プロジェクトJSON保存</button></header><main><p>行をドラッグして並び替えます。既存シーンは削除しません。読み合わせだけ画像を変更し、他のマーカー状態は基準シーンをコピーします。</p><label>挿入する読み合わせ画像<select id="ssPage"></select></label><label>このシーンの後へ挿入<select id="ssAfter"></select></label><label>コピーする基準シーン<select id="ssBase"></select></label><button id="ssInsert">シーンの間に追加</button><ol id="ssList"></ol></main>`;document.body.append(modal);
const style=document.createElement('style');style.textContent=`body.studioMode .scenePane,body.studioMode .utilityPane,body.studioMode .cardPane,body.studioMode .colResizer,body.studioMode #layoutDock,body.studioMode #cardMakerTab,body.studioMode #markerMakerTab,body.studioMode #packAssemblerTab{display:none!important}body.studioMode .app{display:block;min-width:0;height:calc(100vh - 150px)}body.studioMode .workspace{height:100%;padding:12px 24px}body.studioMode .canvasViewport{max-height:none}#studioNav{height:150px;padding:10px 24px;background:#142332;border-bottom:1px solid #547796;color:#fff;overflow:auto}#studioNav nav{display:inline-flex;margin-left:24px;gap:10px}#studioNav button,#sceneStudio button{background:#294560;border:1px solid #61809d;color:#fff;border-radius:5px;padding:7px 12px;margin:3px;cursor:pointer}.stGuide{margin:6px;color:#cadcec;font-size:13px}#studioNav label{display:inline-block;font-size:12px}#studioNav input{width:180px}#sceneStudio[hidden]{display:none}#sceneStudio{position:fixed;inset:0;background:#111923;z-index:2400;color:#fff;overflow:auto}#sceneStudio header{position:sticky;top:0;background:#142332;padding:14px}#sceneStudio main{padding:20px;max-width:1200px;margin:auto}#sceneStudio li{list-style:none;display:flex;align-items:center;gap:12px;border:1px solid #516c83;background:#1b2d40;padding:12px;margin:8px 0;cursor:grab}#sceneStudio li img{width:100px;height:56px;object-fit:contain;background:repeating-conic-gradient(#bbb 0% 25%,#fff 0% 50%) 0/12px 12px}#sceneStudio label{display:block;margin:8px 0}#sceneStudio select{max-width:800px}#ssList{padding:0}`;document.head.append(style);document.body.classList.add('studioMode');
const $=id=>document.getElementById(id);function close(){for(const id of ['cardMaker','markerMaker','packAssembler','sceneStudio','readingStudio'])if($(id))$(id).hidden=true;draw();}function run(fn){return async()=>{try{await fn()}catch(e){alert(e.message);$('stStatus').textContent=e.message}}}
function refreshSceneUI(){const order=model().sceneOrder,ss=data().entities.scenes,selected={after:$('ssAfter').value,base:$('ssBase').value,page:$('ssPage').value};for(const id of ['ssAfter','ssBase']){$(id).innerHTML=order.map(s=>`<option value="${s}">${esc(ss[s].name)}</option>`).join('');if(order.includes(selected[id==='ssAfter'?'after':'base']))$(id).value=selected[id==='ssAfter'?'after':'base'];}$('ssPage').innerHTML=model().readPages.map((p,i)=>`<option value="${p.id}">READ_${String(i+1).padStart(3,'0')}</option>`).join('');if(selected.page)$('ssPage').value=selected.page;$('ssList').innerHTML=order.map((id,i)=>{const s=ss[id],meta=model().sceneMeta[id],img=assets()[s.markers?.reading_panel?.imageUrl]||'';return `<li draggable="true" data-scene="${id}"><b>☰ ${String(i+1).padStart(2,'0')}</b><img src="${img}"><span>${esc(s.name)}<br><small>${meta?'読み合わせ / 基準：'+esc(ss[meta.base]?.name||meta.base):'既存シーン'}</small></span><button data-preview="${id}">表示</button><button data-hide="${id}">読み合わせを透明に</button><button data-up="${id}">↑</button><button data-down="${id}">↓</button></li>`}).join('');for(const row of $('ssList').children){row.ondragstart=e=>e.dataTransfer.setData('text/plain',row.dataset.scene);row.ondragover=e=>e.preventDefault();row.ondrop=e=>{e.preventDefault();reorder(e.dataTransfer.getData('text/plain'),row.dataset.scene)};}
$('ssList').querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>{PackAssembler.model.scene=b.dataset.preview;close();refreshAllEditors()});$('ssList').querySelectorAll('[data-hide]').forEach(b=>b.onclick=run(()=>hideReading(b.dataset.hide)));for(const direction of ['up','down'])$('ssList').querySelectorAll('[data-'+direction+']').forEach(b=>b.onclick=()=>{const id=b.dataset[direction],at=order.indexOf(id),target=order[at+(direction==='up'?-1:1)];if(target){if(direction==='up')reorder(id,target);else reorder(target,id)}});
}
$('stBoard').onclick=()=>{close();GlobalEdit.toggle(true)};$('stCards').onclick=()=>{close();CardMaker.open()};$('stReading').onclick=()=>{close();ReadingStudio.open()};$('stScenes').onclick=()=>{close();refreshSceneUI();modal.hidden=false};$('stSave').onclick=$('ssSave').onclick=saveProject;$('stLoad').onclick=()=>document.getElementById('loadFile').click();$('ssClose').onclick=close;$('ssZip').onclick=run(async()=>downloadBlob(await finalZip(),'FINAL_CCFOLIA.zip'));$('ssPng').onclick=run(async()=>{const c=makeCanvas(1600,900);GlobalEdit.render(c.getContext('2d'));downloadBlob(new Blob([await canvasPngBytes(c)],{type:'image/png'}),'preview.png')});$('ssInsert').onclick=run(async()=>{const page=model().readPages.find(p=>p.id===$('ssPage').value);if(!page)throw Error('先に読み合わせ画像を作ってください');await insert(page,$('ssAfter').value,$('ssBase').value)});
$('stImport').onchange=run(async()=>{const f=$('stImport').files[0];if(!f)return;if(!confirm('現在の作業を入れ替えます。保存済みですか？'))return;const previousState=structuredClone(state),old=structuredClone(state.packAssembler);try{await PackAssembler.importZip(f);const imported=PackAssembler.model.sources.at(-1);if(imported.kind!=='base')throw Error('FINAL_CCFOLIA ZIPを選択してください');state.packAssembler={...old,active:true,sources:[],result:{data:structuredClone(imported.data),assets:imported.assets,fits:{},log:[]},scene:imported.data.entities.room.sceneId};state.studio=undefined;state.cardMaker=undefined;model().sourceHash=await sha256HexBytes(new Uint8Array(await f.arrayBuffer()));model().sceneOrder=Object.keys(imported.data.entities.scenes).sort((a,b)=>imported.data.entities.scenes[a].order-imported.data.entities.scenes[b].order);model().originalScenes=[...model().sceneOrder];state.layoutOverrides.assembled={};await ready();}catch(e){state=previousState;await ready();throw e}});
const previous=refreshAllEditors;refreshAllEditors=function(){previous();if(state.studio&&state.packAssembler?.result){$('stStatus').textContent=`シーン ${Object.keys(data().entities.scenes).length} / アイテム ${Object.keys(data().entities.items).length} / reading_panel同一ID`;if(!modal.hidden)refreshSceneUI();}};
window.Studio={model,data,assets,scene,adjusted,finalZip,insert,hideReading,reorder,addImage,refreshSceneUI,close,openScenes(page){close();refreshSceneUI();if(page)$('ssPage').value=page.id;modal.hidden=false;},ready};ready();
})();
